version: 2.1
jobs:
  print_hello:
    docker:
      - image: cimg/node:19.5.0
    steps:
      - checkout
      - run:
          name: "print_hello"
          command: "echo Hey Hello!"
  print_world:
    docker:
      - image: cimg/node:19.5.0
    steps:
      - checkout
      - run:
          name: "print_world"
          command: "echo World!"
  
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["a6:36:db:10:12:a4:80:f9:21:d2:b3:38:84:a2:9b:19"] 
      - run:
          name: Install Ansible
          command: |
                apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
                ansible-playbook -i inventory.txt main4.yml
  
workflows:
  infrastructure_jobs:
    jobs:
      #- print_hello
      #- print_world
      - configure_infrastructure
          
